
name: Terraform - Provision EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'kubernetes/deployment.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Init, Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::929897439921:role/eks-2048-terraform-githubactions
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./Terrafrom
        run: terraform init

      - name: Terraform Validate
        working-directory: ./Terrafrom
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./Terrafrom
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./Terrafrom
        run: terraform apply -auto-approve tfplan
